### PR TITLE
Image/Video viewing via lightbox2 & html5lightbox

### PR DESCRIPTION
**Pull request by wwwlde**
Image/Video viewing via lightbox2 & html5lightbox

### CODE REVIEW

**Comment by nervo** [comment]
Wow, impressive !!!

But, why both lightbox 2 & html5lightbox ?
And why did'nt you take the last versions of them ?

**Comment by wwwlde** [comment]
> Wow, impressive !!!
> 
> But, why both lightbox 2 & html5lightbox ?

html5lightbox is used for videos.

> And why did'nt you take the last versions of them ?

I made this for my personal photo library few years ago :) It's still work as expected in all modern browsers.

**Comment by wwwlde** [comment]
You can check that everything work correctly :-) Also the use of both libraries is justified, they complement each other(IMHO).

**Comment by erfantkerfan** [comment]
@nervo could you merge plz?

**Pull request closed without merging**
